[package]
name = "hello_receive"
version = "0.1.0"
edition = "2021"

[dependencies]
rustecal = { path = "../../../rustecal", features = ["pubsub"] }
rustecal-types-string = { path = "../../../rustecal-types-string" }
