[package]
name = "rustecal-types-string"
version = "0.1.0"
edition = "2021"
description = "String type support for rustecal TypedPublisher / TypedSubscriber"
license = "Apache-2.0"

[dependencies]
rustecal-core = { path = "../rustecal-core" }
rustecal-pubsub = { path = "../rustecal-pubsub" }
