[package]
name = "rustecal-pubsub"
version = "0.1.0"
edition = "2021"

[dependencies]
rustecal-sys = { path = "../rustecal-sys" }
rustecal-core = { path = "../rustecal-core" }
thiserror     = "1.0"
serde         = { version = "1.0", optional = true }

[features]
default       = []
serde-support = ["serde"]
