[package]
name = "rustecal-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rustecal-sys = { path = "../rustecal-sys" }
once_cell     = "1.17"
thiserror     = "1.0"
bitflags      = "1.3"

[features]
default = []
