[package]
name = "rustecal-types-protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.5"
rustecal-core = { path = "../rustecal-core" }
rustecal-pubsub = { path = "../rustecal-pubsub" }
